version: '3'
services:
  db:
    image: mysql:5.6.34
    ports:
      - "3306:3306"
    volumes:
      - "db-data:/var/lib/mysql/data"
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=rails
  redis:
    image: redis:5.0.7-alpine
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - "nfsmount:/app"
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      REDIS_URL: redis://redis
      DISPLAY: :0
    stdin_open: true
    tty: true
volumes:
  db-data:
  redis-data:
  nfsmount:
    driver: local
    driver_opts:
       type: nfs
       o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
       device: ":$PWD"
