version: '3'
services:
  db:
    image: mysql:5.6.34
    ports:
      - "3306:3306"
    volumes:
      - "db-data:/var/lib/mysql/data"
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=rails
  redis:
    image: redis:5.0.7-alpine
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: ''
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      REDIS_URL: redis://redis
      DISPLAY: :0
    stdin_open: true
    tty: true
  sidekiq:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/app
    environment:
      REDIS_URL: "redis://redis:6379/0"
      REDIS_PASSWORD: ''
    depends_on:
      - app
      - redis
    stdin_open: true
    tty: true
    
volumes:
  db-data:
  redis-data:
